### ISSUE TITLE
Can you please upload V2 (without RSelenium)?

### ISSUE THREAD

**Issue by icu12345** [datruccone/PortfolioEvolution#1]
So I am no R expert but I tried the script out and RSelenium outputs a lot of errors... Instead of trying to figure out what I did wrong it seems much easier to just use the older version where I paste the link manually and don"t use RSelenium...

Thanks...

P.S. Great work, this script looks fantastic!

**Comment by datruccone** [comment]
Hi there, thanks for your words!. 
You can download older versions directly from github, here is the history: https://github.com/datruccone/PortfolioEvolution/commits/master/PortfolioEvolution_Public.R
